services:
  auth:
    image: quay.io/keycloak/keycloak:25.0.6
    command:
      - start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - data:/opt/keycloak/data
      - ./extensions/custom-authenticator/target/custom-authenticator.jar:/opt/keycloak/providers/custom-authenticator.jar
      - ./extensions/external-app-action-token-authenticator/target/external-app-action-token-authenticator.jar:/opt/keycloak/providers/external-app-action-token-authenticator.jar
      - ./extensions/external-app-rest-authenticator/target/external-app-rest-authenticator.jar:/opt/keycloak/providers/external-app-rest-authenticator.jar
      - ./extensions/lib/feign-core-13.5.jar:/opt/keycloak/providers/feign-core-13.5.jar
      - ./extensions/lib/feign-jackson-13.5.jar:/opt/keycloak/providers/feign-jackson-13.5.jar

volumes:
  data: