services:
  auth:
    image: quay.io/keycloak/keycloak:25.0.6
    command:
      - start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - data:/opt/keycloak/data
      - ./extensions/custom-authenticator/target/custom-authenticator.jar:/opt/keycloak/providers/custom-authenticator.jar

volumes:
  data: